# 分段yaml文件中多个dataset transforms配置
---
DatasetTransform:
  labels:
  transform_strategy: ['TOP1_CLASS', 'TOP3_CLASS', 'TOP5_CLASS']

---
MnistTransform:
  labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  transform_strategy: ['TOP1_CLASS', 'TOP3_CLASS', 'TOP5_CLASS']
  resize: [32, 32]
  rescale1:
    rescale_factor: 1 / 0.3081
    shift_factor: -1 * 0.1307 / 0.3081
  rescale2:
    rescale_factor: 1.0 / 255.0
    shift_factor: 0.0

---
Cifar10Transform:
  labels: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
  transform_strategy: ['TOP1_CLASS', 'TOP3_CLASS', 'TOP5_CLASS']
  random_crop:
    size: [32, 32]
    padding: [4, 4, 4, 4]
  random_horizontal_flip:
    prob: 0.5
  resize: [224, 224]
  rescale:
    rescale_factor: 1.0 / 255.0
    shift_factor: 0.0
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]

---
ImageFolderTransform:
  labels: ["Agaricus双孢蘑菇,伞菌目,蘑菇科,蘑菇属,广泛分布于北半球温带,无毒",
           "Amanita毒蝇伞,伞菌目,鹅膏菌科,鹅膏菌属,主要分布于我国黑龙江、吉林、四川、西藏、云南等地,有毒",
           "Boletus丽柄牛肝菌,伞菌目,牛肝菌科,牛肝菌属,分布于云南、陕西、甘肃、西藏等地,有毒",
           "Cortinarius掷丝膜菌,伞菌目,丝膜菌科,丝膜菌属,分布于湖南等地(夏秋季在山毛等阔叶林地上生长)",
           "Entoloma霍氏粉褶菌,伞菌目,粉褶菌科,粉褶菌属,主要分布于新西兰北岛和南岛西部,有毒",
           "Hygrocybe浅黄褐湿伞,伞菌目,蜡伞科,湿伞属,分布于香港(见于松仔园),有毒",
           "Lactarius松乳菇,红菇目,红菇科,乳菇属,广泛分布于亚热带松林地,无毒",
           "Russula褪色红菇,伞菌目,红菇科,红菇属,分布于河北、吉林、四川、江苏、西藏等地,无毒",
           "Suillus乳牛肝菌,牛肝菌目,乳牛肝菌科,乳牛肝菌属,分布于吉林、辽宁、山西、安徽、江西、浙江、湖南、四川、贵州等地,无毒"]
  transform_strategy: ['TOP1_CLASS', 'TOP3_CLASS', 'TOP5_CLASS']
  random_crop_decode_resize:
    size: [224, 224]
    scale: [0.08, 1.0]
    ratio: [0.75, 1.333]
  random_horizontal_flip:
    prob: 0.5
  resize: [256, 256]
  center_crop: [224, 224]
  normalize:
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]

---
VOCTransform:
  labels: ['background',
           'aeroplane', 'bicycle', 'bird', 'boat', 'bottle',
           'bus', 'car', 'cat', 'chair', 'cow',
           'diningtable', 'dog', 'horse', 'motorbike', 'person',
           'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']
  transform_strategy: ['TOP1_CLASS', 'TOP3_CLASS', 'TOP5_CLASS']
  resize: [300, 300]
  horizontal_flip: 1.0
  normalize:
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
  random_color_adjust:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4

---
ShanshuiTransform:
  labels: ['Background',
           'Bird_spp', 'Blue_sheep', 'Glovers_pika', 'Gray_wolf',
           'Himalaya_marmot', 'Red_fox', 'Snow_leopard',
           'Tibetan_snowcock', 'Upland_Buzzard', 'White-lipped_deer']
  transform_strategy: ['TOP1_CLASS', 'TOP3_CLASS', 'TOP5_CLASS']
  resize: [300, 300]
  horizontal_flip: 1.0
  normalize:
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
  random_color_adjust:
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4

---
CycleGanDatasetTransform:
  random_resized_crop:
    size: [256, 256]
    scale: [0.5, 1.0]
    ratio: [0.75, 1.333]
  random_horizontal_flip:
    prob: 0.5
  resize: [256, 256]
  normalize:
    mean: [127.5, 127.5, 127.5]
    std: [127.5, 127.5, 127.5]
